language: python
matrix:
  include:
    - python: 3.4
      env: TOXENV=py34
    - python: 3.4
      env: TOXENV=docs
    - python: 3.5
      env: TOXENV=py35
install:
  - pip install tox
script:
  - tox
